[book]
title = "LFE Quick Start with lfetool"
author = "Duncan McGreggor"
description = "An Introduction to LFE Going Ludicrous Speed"
language = "en"

[build]
build-dir = "docs"

[preprocessor.index]

[preprocessor.links]

[output.html]
additional-css = ["css/custom.css"]

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
